### ISSUE TITLE
Add netlify.toml

### ISSUE THREAD

**Issue by weotch** [BKWLD/create-cloak-app#33]
It should at least have an ignore command like this:

```toml
[build]
	# Trigger redeploys on library changes
	ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../library ./ ../netlify.toml ../yarn.lock"
```

There should be some conditions in there based on whether it's a hybrid site or not.
